apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-secret
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: {{ .Values.dbConnectionString | quote }}
  MSSQL_SA_PASSWORD: {{ .Values.dbPassword | quote }}